### ISSUE TITLE
Ability to visual mark EX eligible gyms on map

### ISSUE THREAD

**Issue by tuckjake** [PokeNavBot/MobileAppBeta#10]
It would be nice if there was someway to visually mark EX eligible gyms on the map.  Even better a way to high light any raids at ex eligible gyms when eggs and raids are reported at them.

**Comment by Nina10e** [comment]
Agreed!  That would be great. Also to maybe X it out those weeks those gyms are locked due to the an ex pass being handed out there for that week.

**Comment by fortepc** [comment]
A simple counter "Gym has hosted X amount of EX Raids in the past 90 days" would be nice in the gym description.
