### ISSUE TITLE
Raid Screenshot OCR via Mobile Device

### ISSUE THREAD

**Issue by KTachyon** [PokeNavBot/MobileAppBeta#11]
**Is your feature request related to a problem? Please describe.**
I feel that the OCR load should actually be distributed to the clients instead of having the server do all the processing.

**Describe the solution you'd like**
The server should act as a raid database and OCR data repo to update the clients on how to perform the processing.

**Describe alternatives you've considered**
Not really an alternative, but the server should still keep it's current functionality for discord channels.

**Comment by dandesousa** [comment]
Absolutely! This is why the app was created -- but doing so is a largish effort. It will both be faster, more data efficient and overall much better. 

All my OCR is outsourced to Google so I need to investigate a bit to make sure the quality is decent but its a high priority feature for sure!

**Comment by dandesousa** [comment]
blocked by #6
