### ISSUE TITLE
Raid Check Ins 

### ISSUE THREAD

**Issue by Nina10e** [PokeNavBot/MobileAppBeta#12]
**Is your feature request related to a problem? Please describe.**
No way to determine via app who is going to be at that raid. 

**Describe the solution you'd like**
App users able to click on app and select going and it will populate that in the discord server. 
Have them be able to click it here. 

![screenshot_20180905-072504_pokenav](https://user-images.githubusercontent.com/43005797/45099712-921e5800-b0ed-11e8-85aa-1256cd44c1e6.jpg)

**Describe alternatives you've considered**
Dual apps which makes it cumbersome. 

**Additional context**

**Comment by dandesousa** [comment]
blocked by #6
