### ISSUE TITLE
Include Raid Counters 

### ISSUE THREAD

**Issue by Nina10e** [PokeNavBot/MobileAppBeta#13]
**Describe the solution you'd like**
Be able to click on the raid boss and it will display best counters to use. 

![screenshot_20180905-072504_pokenav](https://user-images.githubusercontent.com/43005797/45099712-921e5800-b0ed-11e8-85aa-1256cd44c1e6.jpg)

**Comment by dandesousa** [comment]
Need to check with celandro on this one

**Comment by fortepc** [comment]
If you're going to include raid counters, you should include the Perfect CP number for both normal and weather boosted.

**Comment by dandesousa** [comment]
Celandro has OK'd basic counters in the app. So I will be accepting this and including this in a future release

**Comment by Nina10e** [comment]
perfect!  thanks!
