### ISSUE TITLE
Zoom feature does not work

### ISSUE THREAD

**Issue by pikachu1059** [PokeNavBot/MobileAppBeta#14]
**Describe the bug**
When I click on the GPS "zoom" icon, nothing happens

**To Reproduce**
1. Go to 'Map'
2. Click on 'GPS icon.'

**Expected behavior**
I expected it to zoom in on my location when I clicked on the button

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: LG G5
 - OS: Android 7.0
 - App Version Build 1.0.0

**Additional context**

**Comment by dandesousa** [comment]
Does your map show a blue dot indicating your location when it doesn't move -- does it center on the correct location when you first opened the app?

**Comment by pikachu1059** [comment]
Yes it does, The blue dot is at the correct location, just it doesn't zoom in when I press the GPS button. So I have to zoom manually.

**Comment by dandesousa** [comment]
The default zoom is pretty far -- if you pan away or zoom out and then press the button does it work?

**Comment by pikachu1059** [comment]
Nope. Even if it's from far away, it doesn't zoom.

**Comment by dandesousa** [comment]
Believe this is related to #1 -- will keep investigating

**Comment by dandesousa** [comment]
Fixed in 0.1.1
