### ISSUE TITLE
Nearby does not work

### ISSUE THREAD

**Issue by pikachu1059** [PokeNavBot/MobileAppBeta#15]
**Describe the bug**
There's a raid 1.1 km from me and it doesn't show. From what I understand, nearby raids should cover 25-30 km.

**To Reproduce**
Step(s) to reproduce the behavior:
1. Go to 'Nearby'

**Expected behavior**
I would be able to see nearby raids that are 2 km away from me.

**Screenshots**
![image](https://user-images.githubusercontent.com/37431188/45105261-da477580-b101-11e8-93f3-45bf8ff1756c.png)

**Smartphone (please complete the following information):**
 - Device: LG G5
 - OS: 7.0
 - App Version Build 1.0.0

**Additional context**
[](url)

**Comment by dandesousa** [comment]
Do you have a screenshot of your map view showing the nearby raid? Just want to try and reproduce this in an emulator on production data near your location if possible.

**Comment by fortepc** [comment]
I had a similar issue, and it turned out the raid wasn't being properly linked to the gym. Once we used the `$gym` command to link our raid to a specific gym, it showed up. It's not immediately obvious sometimes when the bot isn't able to link to a gym correctly. 

The app will only show raids that have a set timer, have a gym linked, and aren't an EX Raid.

**Comment by dandesousa** [comment]
At your earliest convenience if you can confirm the above two comments with a raid that shows on the map but not on the nearby along with a screenshot of discord showing a link gym -- would be a big help -- its possible you have only partial coverage or a duplicate preventing it from hitting the map

**Comment by pikachu1059** [comment]
![image](https://user-images.githubusercontent.com/37431188/45170673-6d4de180-b1ce-11e8-9960-67227d844afc.png)
![image](https://user-images.githubusercontent.com/37431188/45170695-78a10d00-b1ce-11e8-8c73-ca6dd0891944.png)
![image](https://user-images.githubusercontent.com/37431188/45170709-822a7500-b1ce-11e8-8abe-acc6b3e96f4f.png)
![image](https://user-images.githubusercontent.com/37431188/45170721-89ea1980-b1ce-11e8-88dd-f12eb6ed7e7f.png)

**Comment by dandesousa** [comment]
Believe this is related to #1 -- will keep investigating

**Comment by dandesousa** [comment]
Fixed in 0.1.1
