### ISSUE TITLE
Show hatch time then end time instead of just end time

### ISSUE THREAD

**Issue by emman31** [PokeNavBot/MobileAppBeta#17]
When I click on a raid, it shows when the raid ends.
If the egg is not hatched yet, it may be useful to see when it hatch instead.

**Comment by fortepc** [comment]
This only shows on map view, on nearby view it shows the hatch details, when you click on a raid in the map view, it should bring up the same menu that the nearby menu does.

**Comment by dandesousa** [comment]
The map view **should** show the next "raid event time" IMO. So if the egg hasn't hatched, it should show hatch time. If it has hatched it should show end time. I will get this fixed.
