### ISSUE TITLE
Show a different icon when the egg hatch

### ISSUE THREAD

**Issue by emman31** [PokeNavBot/MobileAppBeta#18]
When an egg hatch, and the boss is not set, there is no way to know by looking at the map.

**Comment by fortepc** [comment]
Make an icon that has the same icon, but a hatched version, with the shells on the ground, appearing as though a question mark is sitting in the broken egg shell.

**Comment by dandesousa** [comment]
May need to ask Velocitrator for some new icons

**Comment by dandesousa** [comment]
Waiting on artwork for this but I have already adjusted some text copy to respond to https://github.com/PokeNavBot/MobileAppBeta/issues/17

and I'll add artwork when ready
