### ISSUE TITLE
Brighter app icon and splash screen

### ISSUE THREAD

**Issue by SenseiSupaku** [PokeNavBot/MobileAppBeta#27]
**Is your feature request related to a problem? Please describe.**
No - It's mostly opinion/preference.

**Describe the solution you'd like**
The new app icon design is fantastic, but it needs to be brighter so that it can stand out next to other apps. Same goes for the splash screen.

**Describe alternatives you've considered**
Leave the icon/splash screen as is.

**Additional context**
This should be a low priority.

**Comment by dandesousa** [comment]
https://github.com/PokeNavBot/MobileAppBeta/issues/7
