### ISSUE TITLE
iPhone X - Raid not displayed in app if posted after hatch

### ISSUE THREAD

**Issue by SenseiSupaku** [PokeNavBot/MobileAppBeta#28]
**Describe the bug**
A raid will not be displayed in the app if it gets posted via screenshot after hatch because the raid time remaining is blocked due to the iPhone X screen aspect ratio.

**To Reproduce**
1.) Post a screenshot of a raid after it has hatched (using an iPhone X) - See attached.
2.) Review the Pokenav map/nearby and it will not be displayed

**Expected behavior**
The raid should be displayed in the app IF there is a way to manually set the time remaining when posting the screenshot. i.e. you wouldn't have to create a channel for the raid and set the time limit yourself.

**Screenshots**
See attached.
![image0](https://user-images.githubusercontent.com/43039605/45165553-142c8080-b1c3-11e8-8d2d-7d8d55544b68.png)

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: 11.4.1
 - App Version Build 1.0.0

**Additional context**
Might already be a known issue.

**Comment by fortepc** [comment]
You can manually set the time in the raid channel on discord. `$set-hatch 10` or $set-despawn 12`.
