### ISSUE TITLE
Raid Did Not Show 

### ISSUE THREAD

**Issue by Nina10e** [PokeNavBot/MobileAppBeta#32]
**Describe the bug**
Posted a lvl 2 egg in discord, checked the app and it never showed up in te app on the nearby or on the map. This has so far only happened once for me. 

**Expected behavior**
All raids reported to discord should be also displayed in the app. 

**Screenshots**

![image](https://user-images.githubusercontent.com/43005797/45223064-d63f6300-b27b-11e8-9ade-603123e229c4.png)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S7 edge 
 - OS: Android 8.0.0
 - App Version Build 1.0.0

**Comment by fortepc** [comment]
When reporting this type of issue please also include a screenshot of the raid in your active raids Channel 

Raids will only show up on nearby or in the map if they are directly linked to a gym and have a valid countdown timer, so having a screenshot of it in the Discord Channel after it has been processed allows the developer to eliminate user error as a possible cause so that he can focus on the root issue.

**Comment by fortepc** [comment]
Grades will only show up on nearby or in the map if they are directly linked to a gym and have a valid countdown timer

**Comment by fortepc** [comment]
And the more information about exactly when and where the raid was, the easier it will make it for the developer to track down the issue.

**Comment by Nina10e** [comment]
Thanks for the tip....I am obviously having a technical difficulty bc I cannot see how I can add a screen shot via my phone on here :(

**Comment by fortepc** [comment]
https://play.google.com/store/apps/details?id=com.fastaccess.github

You can use this app, it may make it a bit easier.

**Comment by Nina10e** [comment]
I am using that one but there is no way that I am seeing to add attachments.

**Comment by fortepc** [comment]
Left side of comment box, upwards facing triangle expands out a tool box, scroll that toolbox to the far right, there will be a gallery icon. Looks like a box/picture with a two peaked mountain on it.

**Comment by Nina10e** [comment]
@fortepc nope that option is not there

**Comment by Nina10e** [comment]
![Raids not showing on map that have been reported on discord![](https://i.imgur.com/LPKlgRV.jpg)

**Comment by Nina10e** [comment]
![](https://i.imgur.com/EzBp0Bx.jpg)

**Comment by Nina10e** [comment]
![](https://i.imgur.com/7gwgHcX.jpg)

**Comment by Nina10e** [comment]
The regirock that is at the sprint gym is not showing up on the app

**Comment by fortepc** [comment]
Nina, you need to also include a screenshot from Discord of the raid being successfully linked to a particular gym. 

specifically you need to show the entry for that particular raid in your active raids Channel. Not just in the channel list.

**Comment by fortepc** [comment]
If the title of the gym in the active raid Channel entry is not clickable, if it doesn't say get directions, then the raid has not been successfully linked to a specific gym. In which case it will not show up on the map.

You need to use the `$gym` command in order to link the gym to the specific raid.

**Comment by fortepc** [comment]
As a note as well, Sprint gyms change their name relatively frequently, so you might have to use the gym command on one of the older names if the database has that older name in it.

**Comment by Nina10e** [comment]
Ths screen shots show when it happened the second time? With the sprint gym...see the discord screen shot above. The OG post the gym that did not get reported was at a cemetry. Since it orginally happened several days ago I last my screen shot from then.

**Comment by fortepc** [comment]
Yes, it only shows the channel listing screenshot. You need the screenshot of the contents of the #active-raids channel. The channel listing you screenshotted can successfully get the gym name, even if the gym matching fails. You need a screenshot of this place 

![image](https://user-images.githubusercontent.com/26149601/45336089-0de62d80-b550-11e8-9404-9acad6155879.png)


See where it says "Directions to Starbucks"? If it doesn't say that, it's not actually linked to a gym, and you need to use the `$gym` command to search and link the gym.

That's what the dev will need to see to know it's a bug, and not just the bot working as intended.

**Comment by Nina10e** [comment]
Happened again just now

**Comment by Nina10e** [comment]
![](https://i.imgur.com/r8tKeVE.jpg)

**Comment by Nina10e** [comment]
![](https://i.imgur.com/bp9cn2I.jpg)

**Comment by Nina10e** [comment]
![](https://i.imgur.com/tLDeF8T.jpg)

**Comment by Nina10e** [comment]
Mt calvary has shown up in their every time except now it's not.

**Comment by Nina10e** [comment]
Mt calvary has shown up in their every time except now it's not.

**Comment by Nina10e** [comment]
It has always shown up before

**Comment by fortepc** [comment]
If possible there's been a new gym in your area that is causing the gym look up to report a duplicate making it unable to just automatically link to a gym. 

This isn't a bug with the app, you just need to use `$gym` to link that raid to the correct gym.

**Comment by Nina10e** [comment]
No. This has happened now to 3 DIFFERENT gyms in 3 DIFFERENT areas in town. 2 of which were at cemeteries which on opposite sides of town and one was the Sprint gym. These gyms have shown on the map before. Just sometimes they don't.

**Comment by fortepc** [comment]
If the "Directions to [gym]" is not showing up that means that the raid is not properly linked to a specific gym, which means it isn't an app bug. as the app is working as intended, only showing raids that have been linked to a specific gym and have an expiration timer. 

If anything it would be a raid bot bug that isn't properly identifying the gym then. So it should be reported to the normal issues repo, or the discord server, not related to the app at all.

Though, I could be totally wrong and the developer could come in at any moment. I'm just trying to help with what I understand :-P and I'm pretty sure that in this particular case the app is functioning as intended, even if the Discord bot isn't.

**Comment by Nina10e** [comment]
no thats not the issue. Raid is posted in Discord, but it is not being posted on the app.

**Comment by fortepc** [comment]
Yes, I understand. My point is that if the raid in Discord does not say "Directions to [Gym]" then the Discord bot does not know exactly what gym it is. As in it does not know where the gym is so it can't display it on the map.

**Comment by fortepc** [comment]
Look at the example I sent you for the Starbucks raid in the active raids list. Underneath the gym name it has a directions button. That's because pokenav knows where that gym is. 

now look at the example you just sent me. It shows the gym name but it does not show a directions button. That means that the rain bot does not know where that gym is. It needs the `$gym` command to be used in its raid party channel to assign that raid to a specific gym. That way PokeNav can know where it is so that it is able to display it on a map.

**Comment by fortepc** [comment]
It means that the OCR and computer vision was able to recognize the gym name, but it wasn't able to match that gym name to a specific location. It wasn't able to find that specific gym in the database or it found multiple matching gyms in the database and didn't know which one to select.

**Comment by Nina10e** [comment]
Just so I am tracking you correctly it should look like this? ![]()

**Comment by Nina10e** [comment]
![](https://i.imgur.com/jd5jsVr.jpg)

**Comment by dandesousa** [comment]
It looks like this was confusing but sorted out -- if not comment again. Otherwise I think developing out the docs to explain this might be better for providing guidance. Thanks @fortepc for all the effort explaining this.
