### ISSUE TITLE
Not seeing raids in my town

### ISSUE THREAD

**Issue by KaiaDeraven** [PokeNavBot/MobileAppBeta#35]
I live between potterville mi and charlotte mi. All of my raiding is in charlotte where my adress and most cases my gps puts me. All im seeing are raids for lansing and east lansing mi.

**Comment by KaiaDeraven** [comment]
It would be nice to see the raids that are up in Charlotte Mi. (I was trying to move my curser when it sent before i was finished)

**Comment by KaiaDeraven** [comment]
It would be nice to see the raids that are up in Charlotte Mi. (I was trying to move my curser when it sent before i was finished)

**Comment by fortepc** [comment]
If you move your map view you can view raids anywhere. I live in Charlotte North Carolina and if I zoom out I can see raids all over the world.

**Comment by KaiaDeraven** [comment]
I can as well. But when i zoom in and look around my city where there are alot of active gyms, it shows no active raids. I even asked the group im in for raids if there were any and there were several active at the time i posted this. They said that it could be because this app is tied to discord and our group uses facebook...but im not sure..

**Comment by dandesousa** [comment]
Yes so the app isn't tied to a scanner, its tied to the PokeNav discord bot which requires your community reporting nearby raids in discord right now.
