### ISSUE TITLE
Unrecoverable Error: Whiteout on App startup every time after logging in with Discord

### ISSUE THREAD

**Issue by fortepc** [PokeNavBot/MobileAppBeta#37]
**Describe the bug**
After logging into the app with discord, my app white screens everytime I launch the app. 

**To Reproduce**
1. Go to the profile icon to log in with discord
2. Be brought to a browser and have to log in with discord, 
3. Be pushed back to PokeNav app where it flashes with the ui briefly before changing to a white screen. Phone is still fully responsive, Nav bar and notif bar is still there, but PokeNav app is totally whited out. 
4. Force close app, and try to launch again does not fix. Briefly shows nearby screen on launch but goes back to white screen a fraction of a second later.
5. Force Stop again and clearing cache also does not solve it. Same exact result. 
6. Clear app storage brings usability back to app, but reseets entire app to freshly installed state with no login.
7. Try to log in again and repeat steps 3-7. 

**Screenshots**
Will provide in comments after

**Smartphone (please complete the following information):**
 - Device: Google Pixel XL (Taimen)
 - OS: Android 9 (Build Number PPR1.180610.009)
 - App Version Build: 0.2.0

**Additional context**
Similar to an issue I have with the Silph Road app when opening certain nests.... which is weird considering these are the only two apps I've ever had this issue with.

**Comment by fortepc** [comment]
![](https://i.imgur.com/NizstCz.png) 

![](https://i.imgur.com/80AQXXj.png)

**Comment by dandesousa** [comment]
I'll do some testing on Android 9.0.0 and see what I can do. Its possible it just has something to do with the way we handle our networking or the underlying auth libraries. We both have react-native apps so its possible it lends itself to that.

This is high priority for me since this is how patrons will authenticate for their benefits.

**Comment by dandesousa** [comment]
This appears to be tied to battery saver mode on some versions of android

**Comment by dandesousa** [comment]
Unable to reproduce in battery save mode on XL 9.0.0 emulator -- confirmed by secondary user that fails in battery saver mode -- following up when a more recent development device becomes available.

**Comment by fortepc** [comment]
Issue still present for me after disabling battery optimization for this app. Even after full reboot.

**Comment by fortepc** [comment]
I can use a debug version of the app if you want to get logs.

**Comment by fortepc** [comment]
Oh. Weird.

**Comment by fortepc** [comment]
So this process that has me working now, picking up from where I left off in the initial report.

1) disabled battery optimization for pokenav
2) force stop pokenav
3) attempt to use failed
4) reboot phone
5) attempt to use it failed.
6) clear app data and cache
7) open pokenav then log in
8) works.

**Comment by fortepc** [comment]
More confusion, more steps to create more weirdness
1) Turn battery optimization back on for pokenav App is already logged in, still works. 
2) Clear cache, force close, try again, app is still logged in, still works,
3) Clear App Data, open app, log back in, app still works. 
4) reboot, try app again, white out. 

Okay, so what I'm learning here is that it takes a reboot for battery optimization changes to kick in. 

I also got a Logcat of step 4, with it not working. Hope it helps.
[PokeNavWhiteOut.txt](https://github.com/PokeNavBot/MobileAppBeta/files/2404268/PokeNavWhiteOut.txt)

**Comment by fortepc** [comment]
[logcat.txt](https://github.com/PokeNavBot/MobileAppBeta/files/2404318/logcat.txt)
If it helps, here is the logcat of the silph road app doing the same thing, whiting out. Except instead of the silph road doing it every time the app loads, it's doing it everytime I open a very specific nest.

**Comment by dandesousa** [comment]
That is extremely helpful, it may be tied to battery saver reducing the capabilities of the app to get geolocation. 

I may have fixed this accidentally in a newer build you don't yet have, as the logs seem to point to an error fetching a piece of location data (something it does immediately after login in).  There was a bug where I was not properly guarding against location data not being found. 

Going to try to get the next build ready soonish so we can see if it cleared this up.

**Comment by fortepc** [comment]
Seems to be fixed in the build I'm running now. The first public play store build.
