### ISSUE TITLE
Map view no zoom or scroll

### ISSUE THREAD

**Issue by screed87** [PokeNavBot/MobileAppBeta#38]
Describe the bug A clear and concise description of what the bug is.

To Reproduce Steps to reproduce the behavior:

Go to Map
Click on anywhere
See error
Expected behavior 
Have an issue that I cannot zoom or scroll around period on the map. I do have the blue dot indicating my position and it centers on it. Also there is a grey bar across the top of the map like it is not fully loading.

Screenshots If applicable, add screenshots to help explain your problem.

![screenshot_20181009-163955](https://user-images.githubusercontent.com/44007628/46754500-387af180-cc88-11e8-8503-3e9ffc701ffa.jpg)

Smartphone (please complete the following information):

Device: OnePlus 6
OS: Android 9.0 (OxygenOS)
App Version: 1.1.0.129

**Comment by dandesousa** [comment]
solved in 1.2.1 and this issue tracker is being deleted.

**Comment by screed87** [comment]
It works thank you very much
