### ISSUE TITLE
Reduce Icon Sizing For Map Markers

### ISSUE THREAD

**Issue by dandesousa** [PokeNavBot/MobileAppBeta#4]
**Is your feature request related to a problem? Please describe.**
The map marker icons are really large, they should be reduced to make it easier to distinguish when many raids are present.

![0](https://user-images.githubusercontent.com/3880281/45097651-54bbc980-b0f1-11e8-8134-3d1ef1bc6c45.jpeg)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fortepc** [comment]
Would like this customizable, or possible changing icon size based on zoom level or icon density.

**Comment by fortepc** [comment]
Raid pin stacking would be also be a great solution to this problem, where if there are a bunch raid icons overlapping each other, they stack up, and when you tap the stack they spread out. 

An example of this can be found in iitc.me's player tracker plugin.
https://iitc.me/desktop/ 
https://static.iitc.me/build/release/plugins/player-tracker.user.js

![image](https://user-images.githubusercontent.com/26149601/45110765-2fd74e80-b111-11e8-9768-5c661e51994a.png)

this image shows a giant stack of many many players all at the same place, the yellow line from the map pin, connecting them to their actual location that they would normally all be stacked on.

**Comment by dandesousa** [comment]
The customizable option / pins stacking I would consider a separate issue -- trying to reduce the asset sizes and make more visible was the intent and its about the be closed, please report it as a separate request ( just in terms of closing this for priorities sake )
