### ISSUE TITLE
App crashes when clicking in map tab

### ISSUE THREAD

**Issue by alternativelee** [PokeNavBot/MobileAppBeta#8]
Android device, software version 8.0.0. App opens in nearby tab and is fine. Toggling to the preferences tab is also fine. Toggling to the map tab causes the app to crash. Force closing and reopening the app causes same issue. Occasionally the world map will load, but moving the map/zooming causes crash as well.

Phone is galaxy s9.

**Comment by dandesousa** [comment]
Have you opted to share crash /diagnostic data with developers in your android settings? Would be helpful in diagnosing the issue as it seems OK loading it on Android 8.0.0 emulator.

https://support.google.com/accounts/answer/6078260
